export enum ErrorCode {
  // Auth
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_OTP_INVALID = 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  AUTH_TOTP_REQUIRED = 'AUTH_TOTP_REQUIRED',
  AUTH_TOTP_INVALID = 'AUTH_TOTP_INVALID',
  AUTH_WEBAUTHN_FAILED = 'AUTH_WEBAUTHN_FAILED',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_FORBIDDEN = 'USER_FORBIDDEN',

  // Todo
  TODO_NOT_FOUND = 'TODO_NOT_FOUND',
  TODO_FORBIDDEN = 'TODO_FORBIDDEN',

  // API Key
  API_KEY_NOT_FOUND = 'API_KEY_NOT_FOUND',
  API_KEY_INVALID = 'API_KEY_INVALID',
  API_KEY_REVOKED = 'API_KEY_REVOKED',

  // Payments
  PAYMENT_STRIPE_ERROR = 'PAYMENT_STRIPE_ERROR',
  PAYMENT_SUBSCRIPTION_NOT_FOUND = 'PAYMENT_SUBSCRIPTION_NOT_FOUND',
  PAYMENT_WEBHOOK_INVALID = 'PAYMENT_WEBHOOK_INVALID',

  // Upload
  UPLOAD_NO_FILE = 'UPLOAD_NO_FILE',
  UPLOAD_TOO_LARGE = 'UPLOAD_TOO_LARGE',
  UPLOAD_INVALID_TYPE = 'UPLOAD_INVALID_TYPE',

  // Feature Flags
  FEATURE_DISABLED = 'FEATURE_DISABLED',
  FEATURE_FLAG_NOT_FOUND = 'FEATURE_FLAG_NOT_FOUND',

  // Organizations
  ORG_NOT_FOUND = 'ORG_NOT_FOUND',
  ORG_FORBIDDEN = 'ORG_FORBIDDEN',
  ORG_ALREADY_MEMBER = 'ORG_ALREADY_MEMBER',
  ORG_INVITATION_NOT_FOUND = 'ORG_INVITATION_NOT_FOUND',
  ORG_INVITATION_EXPIRED = 'ORG_INVITATION_EXPIRED',

  // General
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
