/**
 * Example typed API client using openapi-fetch + generated types.
 *
 * Prerequisites:
 *   1. bun run openapi:codegen   ← exports OpenAPI JSON and generates generated/api.d.ts
 *   2. Copy/import this file into your frontend project.
 *
 * The generated/api.d.ts file is NOT committed — regenerate it whenever the API changes.
 */
import createClient from 'openapi-fetch';
import type { paths } from '../generated/api'; // generated by `bun run openapi:codegen`

const BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3000';

export const apiClient = createClient<paths>({ baseUrl: BASE_URL });

// ─── Auth helpers ─────────────────────────────────────────────────────────────

let accessToken: string | null = null;

export function setAccessToken(token: string) {
  accessToken = token;
}

/** Middleware that injects the Bearer token on every request. */
apiClient.use({
  async onRequest({ request }) {
    if (accessToken) {
      request.headers.set('Authorization', `Bearer ${accessToken}`);
    }
    return request;
  },
});

// ─── Usage examples ──────────────────────────────────────────────────────────

async function example() {
  // Login
  const { data: loginData, error: loginError } = await apiClient.POST('/api/v1/auth/login', {
    body: { email: 'admin@example.com', password: 'password123' },
  });

  if (loginError) throw new Error('Login failed');
  setAccessToken(loginData.data.accessToken);

  // List todos (fully typed response)
  const { data: todosData } = await apiClient.GET('/api/v1/todos', {
    params: { query: { page: 1, limit: 20 } },
  });

  console.log('Todos:', todosData?.data);
}
